spring:
  redis:
    host: 192.168.80.100
    port: 6379
    database: 0
    password: 123456
    timeout: 180000
    lettuce:
      pool:
        max-active: 2000
        max-wait: 50000
        max-idle: -1
        min-idle: 0